### ISSUE TITLE
Bulk

### ISSUE THREAD

**Issue by croovaax** [Defaultik/sms_spoofer#4]
Thanks for the script.
This is not an issue but is it possible to send multiple/bulk sms and how do i code it? thanks

**Comment by Defaultik** [comment]
Hello 👋,
I understand correctly that you want to make a function that sends one message to several people?

**Comment by croovaax** [comment]
> Hello 👋, I understand correctly that you want to make a function that sends one message to several people?
Hello sir, thats correct!

**Comment by Defaultik** [comment]
**I'll try to find time to do this,**
in general, the code itself is not complicated, in the `send_sms` function you can specify the number as a list, and then use the cycle to send an SMS

**Comment by croovaax** [comment]
idk i have to send 1 text at a time. it would be awesome if you could add like a contacts.txt list with numbers that it sends 1 text sms to every single number.

**Comment by Defaultik** [comment]
**Shalom,**
I’m glad to announce that I wrote the function you asked for, the code is ugly, but someday I’ll rewrite it.
