### ISSUE TITLE
Api key geting destinetion

### ISSUE THREAD

**Issue by villan162** [Defaultik/sms_spoofer#5]
where am i get api key f using this sms spoofer

**Comment by Defaultik** [comment]
**Hi,**
you should make an account on [vonage.com](https://ui.idp.vonage.com/ui/auth/registration), there go to the Vonage API Dashboard and get API keys. Good luck!

![chrome_mEJrV3sKIJ](https://github.com/Defaultik/sms_spoofer/assets/83678843/f08516d8-338a-4d3b-a68a-bcb9ae427edd)
