### ISSUE TITLE
What I meant from the Previous issue is that the Python script is not allowing me to send the SMS to other numbers, its only sending to the number I registered with Vonage?

### ISSUE THREAD

**Issue by NoRemorse1011** [Defaultik/sms_spoofer#7]

**Comment by Defaultik** [comment]
Hi,
SMS Spoofer fully uses the Vonage API for sending SMS, the program **cannot** cause failures in sending messages.
Here's a [link](https://www.vonage.com/resources/articles/sms-101-why-messages-fail-to-deliver/) to official Vonage article about SMS Deliver Fail.

**Comment by NoRemorse1011** [comment]
Thats not the case bcuz the message is delivering. It is only allowed to send to the number I register with Vonage, but rejecting for other international numbers.

**Comment by NoRemorse1011** [comment]
My issue is I want the sms to successfully deliver to other numbers, not the one I registered with Vonage.

**Comment by Defaultik** [comment]
I understood you and your problem, I recommend you to write to Vonage support and request it.

**Comment by NoRemorse1011** [comment]
Appreciate that g, I’ll create another issue if I still face a problem

**Comment by Defaultik** [comment]
I was glad to help you!
