### ISSUE TITLE
Whats the difference between sending SMS on your python script than sending SMS on the vonage.com SMS API dashboard? Isn’t it the same thing?

### ISSUE THREAD

**Issue by NoRemorse1011** [Defaultik/sms_spoofer#8]

**Comment by Defaultik** [comment]
There is no difference in **SMS sending**, my tool is created to improve the user experience through my own features. For example: Contacts, Bulk SMS.

**Comment by NoRemorse1011** [comment]
My previous Issue problem was that I had to upgrade to a pro plan to send SMS globally. Is that what you done, was this screenshot https://imgur.com/SOmATqN? the number you registered with Vonage or a different number you sent SMS to after you paid for Vonage pro plan?
